# Generated by Django 3.0.2 on 2020-01-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllUnits',
        ),
    ]
