# Generated by Django 3.0.2 on 2020-01-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_delete_allunits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='faculties',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='programs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='venues',
            options={'managed': False},
        ),
    ]
