# Generated by Django 3.0.2 on 2020-01-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20200116_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faculties',
            options={},
        ),
        migrations.AlterModelOptions(
            name='programs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venues',
            options={},
        ),
    ]
